### ISSUE TITLE
Website Profile Page

### ISSUE THREAD

**Issue by EarthenSky** [CSSS/csss-site-backend#13]
Students can login to the website and make a personal profile or something! Authentication is based off CAS, and there will eventually be an endpoint like `auth/info` to get info about a users account. For the time being, `auth/check` can be used to get student id.

This page will probably only be accessible if the user is logged in. 

I can imagine eventually people will be able to upload a bio, pfp, etc...

**Comment by EarthenSky** [comment]
Add support for the backend api call `auth/info` (or something similar, feel free to decide on naming). In addition to computing ID, include the date the student first authenticated to the website & most recently authenticated. 

The profile page should display something like "First login March 21, 2024, Last login May 1, 2024".

This issue depends on a User table being created in the database, which stores info for each user. I forsee this table being used by many issues, so please wait for #14 to be completed.

**Comment by micahdbak** [comment]
@EarthenSky is this the task you assigned me in the W3 Committee meeting? I remember it being something diff

Anyways I'll try and work on this soon :DDD

**Comment by EarthenSky** [comment]
Yeah, this is the one! Though I also asked you to review #10 briefly

**Comment by micahdbak** [comment]
Helper functions in raspberry are done, what's TODO is a profile component 🥳
