### ISSUE TITLE
Store Executive info in table

### ISSUE THREAD

**Issue by EarthenSky** [CSSS/csss-site-backend#16]
We'll want a table to store executive term info and executive student info. The executive student info will link to all the terms a student was an executive, and the students table will link to an executive student entry.

Will also want to introduce API endpoints for unauthenticated & authenticated users to access data they have privileges for. Only execs from the past 5 exec terms can access data. 

TODO
- [x] figure out how the current site computes "exec term"
- [x] create tables
- [x] create endpoints that check authentication, using the permissions subsystem
- [x] create mock data for testing locally (figure out how to do this with alembic)

**Comment by EarthenSky** [comment]
A diagram of the database schema for the site https://drive.google.com/file/d/11Tqg_PGDp6AeEZZTMg8Ebt5_vCzZUfSz/view?usp=sharing

**Comment by micahdbak** [comment]
chop chop geb

**Comment by micahdbak** [comment]
chop chop!

**Comment by EarthenSky** [comment]
Vegetables are being chopped

**Comment by EarthenSky** [comment]
Not all required officers endpoints have been implemented yet
