### ISSUE TITLE
control access of users to github

### ISSUE THREAD

**Issue by EarthenSky** [CSSS/csss-site-backend#20]
execs need to be automatically be added and/or removed from the github organization

You'll have to do some research into github's http api. Doing it async like with discord should be fine for now! If you can think of a better way to do it that would take a while, please make a new issue!

requirements:
- functions to add and remove github users from an org
- functions to add users to & from teams in a github org
- a module, just like the discord one
- vibe with us about what constraints the api has

**Comment by DerpyWasHere** [comment]
Do we ever intend on automating the transfer of sysadmin or is just adding people as regular members sufficient?

**Comment by EarthenSky** [comment]
I think transfer of sysadmin should be triggered manually, but I think having code do the actual updating would be nice
