### ISSUE TITLE
Get discord id & server nickname given a username.

### ISSUE THREAD

**Issue by EarthenSky** [CSSS/csss-site-backend#38]
We want new executives to input their discord username, then for us to figure out their nickname in the CSSS Discord (or if they're not in the CSSS discord) & their discord id.

If the user is not in the CSSS Discord, we'll ask them to join first.

This is related to officer automation, so it should have a (slightly) higher priority.

**Comment by DerpyWasHere** [comment]
Should this be a function or an api like #31? 

As mentioned in the discord bot thread, this is easy to do using the [/guilds/{guild.id}/members/search](https://discord.com/developers/docs/resources/guild#search-guild-members) endpoint. We can just put in a partial username for searching too.

I have an implementation as described in 3a9b6629df171481f4917c75261cfa2321cf9366.

**Comment by EarthenSky** [comment]
> Should this be a function or an api like as in #31?

A function, as it would be used by other endpoints.

> As mentioned in the discord bot thread, this is easy to do using the [/guilds/{guild.id}/members/search](https://discord.com/developers/docs/resources/guild#search-guild-members) endpoint. We can just put in a partial username for searching too.

Cool! We'll want to make sure that the username matches exactly for this case, but it'll be cool if we want to add searching to the dashboard.
