### ISSUE TITLE
Add limit to number of discord API requests per second

### ISSUE THREAD

**Issue by EarthenSky** [CSSS/csss-site-backend#42]
The discord API has a limit per second of 50 API requests. Unfortunately, many actions we want to take requires more than a single API request, and so a single user spamming a button might result in us hitting this limit.

Of course, the frontend should be careful with calling endpoints too quickly, but we should put a safeguard to stop this. A python threading lock + a counter to see how many API calls have been made every second would be a nice addition. If a 51st request is about to be made, sleep for 1s to avoid the penalty (or however long to not hit the discord limit).

There is also a limit per 10 minutes, which we don't want to hit either.

**Comment by DerpyWasHere** [comment]
On any request, Discord's API returns headers which contain the following fields:

- X-RateLimit-Limit (Total number of requests that can be made)
- X-RateLimit-Remaining (Number of requests left before returning 429)
- X-RateLimit-Reset (Time at which the remaining number of requests resets in epoch time)
- X-RateLimit-Reset-After (Time remaining until the number of requests resets)
- X-RateLimit-Bucket (String identifying what resource is being rate limited)

These would be ideal to base our limiting behaviour on.

**Comment by EarthenSky** [comment]
oh beautiful, so we shouldn't even need to do anything too fancy!
